"""initial schema

Revision ID: abcf27a8eb3f
Revises: 
Create Date: 2026-04-01 18:02:38.409011

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'abcf27a8eb3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_source_id'), 'ingestion_logs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_logs_status'), 'ingestion_logs', ['status'], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ioc_value', sa.String(length=2048), nullable=False),
    sa.Column('ioc_type', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('false_positive_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ioc_value', 'ioc_type', name='uq_ioc_value_type')
    )
    op.create_index(op.f('ix_iocs_ioc_type'), 'iocs', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_ioc_value'), 'iocs', ['ioc_value'], unique=False)
    op.create_index('ix_iocs_value_type', 'iocs', ['ioc_value', 'ioc_type'], unique=False)
    op.create_table('source_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('source_weight', sa.Float(), nullable=False),
    sa.Column('lambda_ip', sa.Float(), nullable=False),
    sa.Column('lambda_domain', sa.Float(), nullable=False),
    sa.Column('lambda_hash', sa.Float(), nullable=False),
    sa.Column('lambda_url', sa.Float(), nullable=False),
    sa.Column('last_ingestion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingestion_count', sa.Integer(), nullable=False),
    sa.Column('last_ingestion_error', sa.Text(), nullable=True),
    sa.Column('cumulative_fp_count', sa.Integer(), nullable=False),
    sa.Column('cumulative_tp_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ioc_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ioc_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('first_seen_by_source', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_by_source', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_tags', sa.Text(), nullable=False),
    sa.Column('confidence_raw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ioc_id', 'source_id', name='uq_ioc_source')
    )
    op.create_index(op.f('ix_ioc_observations_ioc_id'), 'ioc_observations', ['ioc_id'], unique=False)
    op.create_index(op.f('ix_ioc_observations_source_id'), 'ioc_observations', ['source_id'], unique=False)
    op.create_table('verdict_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ioc_id', sa.Uuid(), nullable=False),
    sa.Column('analyst_verdict', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdict_feedback_analyst_verdict'), 'verdict_feedback', ['analyst_verdict'], unique=False)
    op.create_index(op.f('ix_verdict_feedback_ioc_id'), 'verdict_feedback', ['ioc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema upgrades."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdict_feedback_ioc_id'), table_name='verdict_feedback')
    op.drop_index(op.f('ix_verdict_feedback_analyst_verdict'), table_name='verdict_feedback')
    op.drop_table('verdict_feedback')
    op.drop_index(op.f('ix_ioc_observations_source_id'), table_name='ioc_observations')
    op.drop_index(op.f('ix_ioc_observations_ioc_id'), table_name='ioc_observations')
    op.drop_table('ioc_observations')
    op.drop_table('source_configs')
    op.drop_index('ix_iocs_value_type', table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_value'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_type'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_index(op.f('ix_ingestion_logs_status'), table_name='ingestion_logs')
    op.drop_index(op.f('ix_ingestion_logs_source_id'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    # ### end Alembic commands ###
